### ISSUE TITLE
How to add a new font

### ISSUE THREAD

**Issue by CHTUZKI** [terjeio/Display-libraries#1]
HI.

I want to use the "Display-libraries" library. I found that there are no Chinese fonts in this library. I want to add Chinese fonts. I read the introduction in readme and tried to use "H. Reddmann" to build the fonts I need. I found that I Will not use "font editor" myself. I tried to find help in the "mikrocontroller" website, but I couldn't find it. Can you give me some help.

The topic of "glcd fontcreator aktuell" was founded in 2008 for a long time, and no relevant help can be found in Google.

Thank you~~

**Comment by terjeio** [comment]
Chinese fonts require multi byte character support, not available in this library. So I am afraid you will have to switch to a different library as adding multi-byte support is, AFAIK, not easily done.

**Comment by CHTUZKI** [comment]
Thank you for your answer
